/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Шаг 1 - Ввод email (общий для входа и регистрации)
         * @description Принимает email и определяет следующие шаги:
         *     - Если пользователь существует и у него есть пароль: возвращает next_step = "password"
         *     - Если пользователь существует, но пароля нет: отправляет OTP и возвращает next_step = "otp"
         *     - Если пользователь не существует: отправляет OTP и возвращает next_step = "signup_slug"
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description Информация о следующих шагах */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginInitResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                429: components["responses"]["RateLimitExceeded"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Шаг 2 - Вход по паролю (опционально)
         * @description Выполняет вход пользователя по паролю.
         *     Используется только если у пользователя установлен пароль (has_password = true).
         *     При успешной верификации возвращает access token.
         *     Refresh token устанавливается в HTTP-only cookie.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginPasswordRequest"];
                };
            };
            responses: {
                /** @description Успешный вход */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["WrongPassword"];
                404: components["responses"]["UserNotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login/otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Шаг 2 - Вход по OTP коду
         * @description Проверяет OTP код и выполняет вход пользователя в систему.
         *     Используется если у пользователя нет пароля или он выбрал вход по OTP.
         *     При успешной верификации возвращает access token.
         *     Refresh token устанавливается в HTTP-only cookie.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginVerifyOtpRequest"];
                };
            };
            responses: {
                /** @description Успешный вход */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LoginResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["InvalidOtp"];
                404: components["responses"]["UserNotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup/slug": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Шаг 2 - Ввод slug для регистрации
         * @description Проверяет доступность slug и сохраняет его для процесса регистрации.
         *     Используется только если пользователь не существует (user_exists = false из /auth/login).
         *     После успешного запроса пользователь должен ввести OTP код на следующем шаге.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SignupEnterSlugRequest"];
                };
            };
            responses: {
                /** @description Slug доступен и сохранен */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /** @example true */
                            success: boolean;
                        };
                    };
                };
                400: components["responses"]["InvalidSlugFormat"];
                409: components["responses"]["SlugAlreadyTaken"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Шаг 3 - Верификация OTP и завершение регистрации
         * @description Проверяет OTP код и завершает регистрацию нового пользователя.
         *     Используется только для регистрации (после ввода slug).
         *     При успешной верификации создается новый профиль и возвращается access token.
         *     Refresh token устанавливается в HTTP-only cookie.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SignupVerifyOtpRequest"];
                };
            };
            responses: {
                /** @description Успешная регистрация */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SignupResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["InvalidOtp"];
                409: components["responses"]["EmailAlreadyExists"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Шаг 1 - Запрос на смену пароля
         * @description Отправляет код подтверждения на email пользователя для смены пароля.
         *     Требует аутентификации. После успешного запроса пользователь должен ввести OTP код на следующем шаге.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChangePasswordRequest"];
                };
            };
            responses: {
                /** @description Код подтверждения успешно отправлен на email */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SendOtpResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                404: components["responses"]["UserNotFound"];
                429: components["responses"]["RateLimitExceeded"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password/change/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Шаг 2 - Верификация OTP и смена пароля
         * @description Проверяет OTP код и изменяет пароль пользователя.
         *     Требует аутентификации.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChangePasswordVerifyOtpRequest"];
                };
            };
            responses: {
                /** @description Пароль успешно изменен */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChangePasswordResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["InvalidOtp"];
                404: components["responses"]["UserNotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password/add": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Шаг 1 - Запрос на добавление пароля
         * @description Отправляет код подтверждения на email пользователя для добавления пароля к аккаунту.
         *     Требует аутентификации. После успешного запроса пользователь должен ввести OTP код на следующем шаге.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AddPasswordRequest"];
                };
            };
            responses: {
                /** @description Код подтверждения успешно отправлен на email */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SendOtpResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                429: components["responses"]["RateLimitExceeded"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/password/add/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Шаг 2 - Верификация OTP и добавление пароля
         * @description Проверяет OTP код и добавляет пароль к аккаунту пользователя.
         *     Требует аутентификации.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["AddPasswordVerifyOtpRequest"];
                };
            };
            responses: {
                /** @description Пароль успешно добавлен */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["AddPasswordResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["InvalidOtp"];
                404: components["responses"]["UserNotFound"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/email/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Шаг 1 - Запрос на смену email
         * @description Отправляет код подтверждения на новый email адрес для смены email пользователя.
         *     Требует аутентификации (bearer token подтверждает владение аккаунтом).
         *     Уведомление о попытке смены email отправляется на текущий (старый) email адрес.
         *     После успешного запроса пользователь должен ввести OTP код на следующем шаге.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChangeEmailRequest"];
                };
            };
            responses: {
                /** @description Код подтверждения успешно отправлен на новый email. Уведомление отправлено на старый email. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SendOtpResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["Unauthorized"];
                409: components["responses"]["EmailAlreadyExists"];
                429: components["responses"]["RateLimitExceeded"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/email/change/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Шаг 2 - Верификация OTP и смена email
         * @description Проверяет OTP код, отправленный на новый email, и изменяет email пользователя.
         *     Требует аутентификации. После успешной смены email пользователь должен будет использовать новый email для входа.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChangeEmailVerifyOtpRequest"];
                };
            };
            responses: {
                /** @description Email успешно изменен */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChangeEmailResponse"];
                    };
                };
                400: components["responses"]["ValidationError"];
                401: components["responses"]["InvalidOtp"];
                404: components["responses"]["UserNotFound"];
                409: components["responses"]["EmailAlreadyExists"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/slug/check": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Проверка доступности slug
         * @description Проверяет доступность slug для использования.
         *     Можно использовать без аутентификации для проверки перед регистрацией.
         */
        get: {
            parameters: {
                query: {
                    /**
                     * @description URL-слаг для проверки доступности
                     * @example username
                     */
                    slug: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Результат проверки доступности */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CheckSlugAvailabilityResponse"];
                    };
                };
                400: components["responses"]["InvalidSlugFormat"];
                500: components["responses"]["InternalServerError"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/slug/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Смена slug профиля
         * @description Изменяет slug профиля пользователя.
         *     Требует аутентификации. Можно изменить только раз в 7 дней.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChangeSlugRequest"];
                };
            };
            responses: {
                /** @description Slug успешно изменен */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ChangeSlugResponse"];
                    };
                };
                400: components["responses"]["InvalidSlugFormat"];
                401: components["responses"]["Unauthorized"];
                403: components["responses"]["SlugChangeLimitExceeded"];
                409: components["responses"]["SlugAlreadyTaken"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Обновление access token
         * @description Обновляет access token используя refresh token из HTTP-only cookie.
         *     Новый refresh token устанавливается в HTTP-only cookie.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["RefreshTokenRequest"];
                };
            };
            responses: {
                /** @description Токен успешно обновлен */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["RefreshTokenResponse"];
                    };
                };
                401: components["responses"]["InvalidRefreshToken"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Выход из системы
         * @description Инвалидирует refresh token из HTTP-only cookie и все связанные токены пользователя.
         *     Требует аутентификации через refresh token в cookie.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: {
                content: {
                    "application/json": components["schemas"]["LogoutRequest"];
                };
            };
            responses: {
                /** @description Успешный выход из системы */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["LogoutResponse"];
                    };
                };
                401: components["responses"]["InvalidRefreshToken"];
                500: components["responses"]["InternalServerError"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Profile: {
            /**
             * @description Уникальный идентификатор профиля (UUID или другой уникальный идентификатор)
             * @example 550e8400-e29b-41d4-a716-446655440000
             */
            id: string;
            /**
             * @description Имя профиля
             * @example John Doe
             */
            name: string;
            /**
             * @description URL-слаг профиля. Должен содержать только строчные латинские буквы,
             *     цифры, дефисы и подчеркивания. Не может начинаться или заканчиваться
             *     на дефис или подчеркивание. Должен быть уникальным.
             * @example johndoe
             */
            slug: string;
            /**
             * Format: email
             * @description Email пользователя
             * @example user@example.com
             */
            email: string;
            /**
             * Format: date-time
             * @description Дата создания профиля
             */
            created_at: string;
            /**
             * Format: uri
             * @description URL аватара профиля. Должен быть валидным HTTP/HTTPS URL.
             * @example https://example.com/avatar.jpg
             */
            avatar_url?: string | null;
            /** @description Защищен ли профиль паролем */
            protected_by_password: boolean;
            /**
             * @description Краткое описание профиля
             * @example Software developer and designer
             */
            short_description: string;
            /** @description Полное описание профиля в формате TipTap JSON. Может быть null или JSONContent. */
            description?: components["schemas"]["JSONContent"] | null;
            theme: components["schemas"]["ProfileTheme"];
            /**
             * @description Массив социальных сетей. Максимум 20 элементов.
             *     Порядок (order) должен быть уникальным для каждого элемента.
             */
            social_media: components["schemas"]["SocialMediaItem"][];
            /**
             * @description Массив блоков Bento. Максимум 50 элементов.
             *     ID и порядок (order) должны быть уникальными для каждого блока.
             */
            bento: components["schemas"]["BentoBlock"][];
        };
        ProfileMainEditableFields: {
            name: string;
            slug: string;
            /** Format: email */
            email: string;
            /** Format: date-time */
            created_at: string;
            /** Format: uri */
            avatar_url?: string | null;
            protected_by_password: boolean;
            short_description: string;
            /** @description Полное описание профиля в формате TipTap JSON. Может быть null или JSONContent. */
            description?: components["schemas"]["JSONContent"] | null;
            theme: components["schemas"]["ProfileTheme"];
            social_media: components["schemas"]["SocialMediaItem"][];
            bento: components["schemas"]["BentoBlock"][];
        };
        ProfileTheme: {
            font: components["schemas"]["Font"];
            theme: components["schemas"]["Theme"];
            /** @description Показывать ли размытие аватара */
            show_avatar_blur: boolean;
            /**
             * @description Радиус скругления границ в пикселях
             * @example 24
             */
            border_radius: number;
            /**
             * @description Ширина границы в пикселях
             * @example 1
             */
            border_width: number;
        };
        /**
         * @description Доступные шрифты
         * @enum {string}
         */
        Font: "open-runde" | "inter" | "gilroy" | "vollkorn" | "jetbrains-mono" | "montserrat" | "oswald" | "caveat";
        /**
         * @description Доступные темы оформления
         * @enum {string}
         */
        Theme: "light" | "dark" | "green" | "pink" | "blue" | "purple" | "golden" | "dark-blue" | "dark-slate" | "dark-forest" | "dark-plum" | "dark-amber" | "dark-ink" | "dark-copper" | "dark-olive" | "dark-indigo" | "teal" | "coral" | "lavender" | "sand" | "mint" | "sky" | "ice" | "peach";
        SocialMediaItem: {
            platform: components["schemas"]["SocialMediaPlatform"];
            /**
             * @description Идентификатор пользователя на платформе
             * @example johndoe
             */
            slug: string;
            /**
             * @description Порядок отображения. Должен быть уникальным в массиве social_media.
             * @example 0
             */
            order: number;
        };
        /**
         * @description Доступные платформы социальных сетей
         * @enum {string}
         */
        SocialMediaPlatform: "instagram" | "telegram" | "x" | "bluesky" | "discord" | "dribbble" | "facebook" | "github" | "linkedin" | "tiktok" | "threads" | "pinterest" | "medium" | "youtube" | "messenger" | "reddit" | "snapchat" | "spotify" | "tumblr" | "twitch" | "vk" | "whatsapp";
        BentoBlock: components["schemas"]["BentoBlockGallery"] | components["schemas"]["BentoBlockLink"] | components["schemas"]["BentoBlockText"] | components["schemas"]["BentoBlockMap"];
        BentoBlockBase: {
            /** @description Уникальный идентификатор блока. Должен быть уникальным в массиве bento. */
            id: string;
            size: components["schemas"]["BentoBlockSize"];
            /**
             * @description Порядок отображения блока. Должен быть уникальным в массиве bento.
             * @example 0
             */
            order: number;
            style: components["schemas"]["BentoBlockStyle"];
            type: components["schemas"]["BentoBlockType"];
        };
        BentoBlockGallery: components["schemas"]["BentoBlockBase"] & {
            /** @enum {string} */
            type?: "gallery";
            properties?: components["schemas"]["BentoBlockPropertiesGallery"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "gallery";
        };
        BentoBlockLink: components["schemas"]["BentoBlockBase"] & {
            /** @enum {string} */
            type?: "link";
            properties?: components["schemas"]["BentoBlockPropertiesLink"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "link";
        };
        BentoBlockText: components["schemas"]["BentoBlockBase"] & {
            /** @enum {string} */
            type?: "text";
            properties?: components["schemas"]["BentoBlockPropertiesText"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "text";
        };
        BentoBlockMap: components["schemas"]["BentoBlockBase"] & {
            /** @enum {string} */
            type?: "map";
            properties?: components["schemas"]["BentoBlockPropertiesMap"];
        } & {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "map";
        };
        /**
         * @description Размер блока Bento
         * @enum {string}
         */
        BentoBlockSize: "2x2" | "4x1" | "2x4" | "4x2" | "4x4" | "dynamic";
        /**
         * @description Стиль блока Bento
         * @enum {string}
         */
        BentoBlockStyle: "plain" | "shadow" | "outline" | "transparent";
        /**
         * @description Тип блока Bento
         * @enum {string}
         */
        BentoBlockType: "gallery" | "link" | "text" | "map";
        BentoBlockPropertiesGallery: {
            /**
             * @description Массив URL изображений для галереи
             * @example [
             *       "https://example.com/image1.jpg",
             *       "https://example.com/image2.jpg"
             *     ]
             */
            media: string[];
        };
        BentoBlockPropertiesLink: {
            /**
             * Format: uri
             * @description URL ссылки. Должен быть валидным HTTP/HTTPS URL.
             * @example https://example.com
             */
            url: string;
            /**
             * @description Заголовок ссылки
             * @example My Website
             */
            title: string;
            /** @description Валидна ли ссылка (проверяется на сервере) */
            url_valid: boolean;
        };
        BentoBlockPropertiesText: {
            /**
             * @description Содержимое текстового блока в формате TipTap JSON.
             *     Максимальный размер JSON: 50KB (50,000 символов в сериализованном виде).
             */
            content: components["schemas"]["JSONContent"] | null;
        };
        BentoBlockPropertiesMap: {
            theme: components["schemas"]["BentoBlockMapThemesOptions"];
            /** @description Показывать ли подписи на карте */
            labels: boolean;
            /** @description Разрешены ли взаимодействия с картой (зум, перетаскивание) */
            interactions: boolean;
            /**
             * @description Уровень масштабирования карты (0 - минимальный, 22 - максимальный)
             * @default 11
             * @example 11
             */
            zoom: number;
            /**
             * @description Заголовок карты
             * @example My Location
             */
            title: string;
            titleAlign: components["schemas"]["BentoBlockMapTitleAlign"];
            /**
             * Format: float
             * @description Широта центра карты в градусах (WGS84)
             * @example 55.7558
             */
            latitude: number;
            /**
             * Format: float
             * @description Долгота центра карты в градусах (WGS84)
             * @example 37.6173
             */
            longitude: number;
        };
        /**
         * @description Тема карты (auto означает автоматический выбор на основе темы профиля)
         * @enum {string}
         */
        BentoBlockMapThemesOptions: "auto" | "light" | "dark" | "positron";
        /**
         * @description Выравнивание заголовка карты
         * @enum {string}
         */
        BentoBlockMapTitleAlign: "bottom-left" | "bottom-center" | "bottom-right" | "top-left" | "top-center" | "top-right";
        /**
         * @description Структурированный JSON контент из TipTap редактора.
         *     Максимальный размер JSON: 50KB (50,000 символов в сериализованном виде).
         */
        JSONContent: {
            /** @description Тип узла (doc, paragraph, heading, text и т.д.) */
            type?: string;
            /** @description Атрибуты узла. Могут содержать любые JSON-сериализуемые значения. */
            attrs?: {
                [key: string]: unknown;
            };
            /** @description Дочерние узлы. Узел может содержать другие узлы. */
            content?: components["schemas"]["JSONContent"][];
            /** @description Список марок узла. Инлайн-узлы могут иметь марки. */
            marks?: components["schemas"]["JSONContentMark"][];
            /**
             * @description Текстовое содержимое узла. Это свойство присутствует только у текстовых узлов
             *     (т.е. узлов с type: 'text'). Текстовые узлы не могут иметь дочерних узлов,
             *     но могут иметь марки.
             */
            text?: string;
        } & {
            [key: string]: unknown;
        };
        JSONContentMark: {
            /** @description Тип марки (bold, italic, link и т.д.) */
            type: string;
            /** @description Атрибуты марки. Могут содержать любые JSON-сериализуемые значения. */
            attrs?: {
                [key: string]: unknown;
            };
        } & {
            [key: string]: unknown;
        };
        LoginRequest: {
            /**
             * Format: email
             * @description Email пользователя для входа
             * @example user@example.com
             */
            email: string;
        };
        LoginVerifyOtpRequest: {
            /**
             * Format: email
             * @description Email пользователя
             * @example user@example.com
             */
            email: string;
            /**
             * @description Код подтверждения из 6 цифр
             * @example 123456
             */
            otp: string;
        };
        /**
         * @description Refresh token устанавливается в HTTP-only cookie с именем `refresh_token`.
         *     Cookie имеет флаги HttpOnly, Secure и SameSite=Strict для безопасности.
         */
        LoginResponse: {
            /** @description JWT токен доступа */
            access_token: string;
        };
        LoginInitResponse: {
            /**
             * @description Существует ли пользователь с таким email
             * @example true
             */
            user_exists: boolean;
            /**
             * @description Есть ли у пользователя пароль (только если user_exists = true)
             * @example true
             */
            has_password?: boolean;
            /**
             * @description Следующий шаг для пользователя:
             *     - password - ввод пароля (если user_exists = true и has_password = true)
             *     - otp - ввод OTP кода (если user_exists = true и has_password = false)
             *     - signup_slug - ввод slug для регистрации (если user_exists = false)
             * @example password
             * @enum {string}
             */
            next_step: "password" | "otp" | "signup_slug";
            /**
             * Format: date-time
             * @description Время истечения OTP кода (если отправлен OTP)
             * @example 2024-01-01T12:00:00Z
             */
            expires_at?: string | null;
        };
        LoginPasswordRequest: {
            /**
             * Format: email
             * @description Email пользователя
             * @example user@example.com
             */
            email: string;
            /**
             * @description Пароль пользователя
             * @example MyPassword123
             */
            password: string;
        };
        SignupRequest: {
            /**
             * Format: email
             * @description Email пользователя для регистрации
             * @example user@example.com
             */
            email: string;
        };
        SignupEnterSlugRequest: {
            /**
             * Format: email
             * @description Email пользователя
             * @example user@example.com
             */
            email: string;
            /**
             * @description URL-слаг профиля. Должен содержать только строчные латинские буквы,
             *     цифры, дефисы и подчеркивания. Не может начинаться или заканчиваться
             *     на дефис или подчеркивание.
             * @example username
             */
            slug: string;
        };
        SignupVerifyOtpRequest: {
            /**
             * Format: email
             * @description Email пользователя
             * @example user@example.com
             */
            email: string;
            /**
             * @description URL-слаг профиля
             * @example username
             */
            slug: string;
            /**
             * @description Код подтверждения из 6 цифр
             * @example 123456
             */
            otp: string;
        };
        /**
         * @description Refresh token устанавливается в HTTP-only cookie с именем `refresh_token`.
         *     Cookie имеет флаги HttpOnly, Secure и SameSite=Strict для безопасности.
         */
        SignupResponse: {
            /** @description JWT токен доступа */
            access_token: string;
        };
        SendOtpRequest: {
            /**
             * Format: email
             * @description Email для отправки кода подтверждения
             * @example user@example.com
             */
            email: string;
        };
        SendOtpResponse: {
            /** @description Успешно ли отправлен код */
            success: boolean;
            /**
             * Format: date-time
             * @description Время истечения кода подтверждения
             */
            expires_at: string;
        };
        ChangePasswordRequest: {
            /** @description Текущий пароль пользователя */
            old_password: string;
            /**
             * @description Новый пароль. Должен содержать минимум 8 символов,
             *     минимум одну заглавную букву, одну строчную букву и одну цифру.
             *     Новый пароль должен отличаться от старого пароля.
             */
            new_password: string;
            /** @description Подтверждение нового пароля (должно совпадать с new_password) */
            confirm_password: string;
        };
        ChangePasswordVerifyOtpRequest: {
            /**
             * Format: email
             * @description Email пользователя
             * @example user@example.com
             */
            email: string;
            /**
             * @description Код подтверждения из 6 цифр
             * @example 123456
             */
            otp: string;
            /** @description Новый пароль */
            new_password: string;
        };
        ChangePasswordResponse: {
            /** @description Успешно ли изменен пароль */
            success: boolean;
        };
        AddPasswordRequest: {
            /**
             * @description Новый пароль. Должен содержать минимум 8 символов,
             *     минимум одну заглавную букву, одну строчную букву и одну цифру.
             */
            new_password: string;
            /** @description Подтверждение нового пароля (должно совпадать с new_password) */
            confirm_password: string;
        };
        AddPasswordVerifyOtpRequest: {
            /**
             * Format: email
             * @description Email пользователя
             * @example user@example.com
             */
            email: string;
            /**
             * @description Код подтверждения из 6 цифр
             * @example 123456
             */
            otp: string;
            /** @description Новый пароль */
            new_password: string;
        };
        AddPasswordResponse: {
            /** @description Успешно ли добавлен пароль */
            success: boolean;
        };
        ChangeEmailRequest: {
            /**
             * Format: email
             * @description Новый email адрес
             * @example newemail@example.com
             */
            new_email: string;
        };
        ChangeEmailVerifyOtpRequest: {
            /**
             * Format: email
             * @description Новый email адрес
             * @example newemail@example.com
             */
            new_email: string;
            /**
             * @description Код подтверждения из 6 цифр, отправленный на новый email
             * @example 123456
             */
            otp: string;
        };
        ChangeEmailResponse: {
            /** @description Успешно ли изменен email */
            success: boolean;
            /**
             * Format: email
             * @description Новый email адрес
             * @example newemail@example.com
             */
            email: string;
        };
        ChangeSlugRequest: {
            /**
             * @description Новый URL-слаг профиля. Должен содержать только строчные латинские буквы,
             *     цифры, дефисы и подчеркивания. Не может начинаться или заканчиваться
             *     на дефис или подчеркивание. Можно изменить только раз в 7 дней.
             * @example newusername
             */
            slug: string;
        };
        ChangeSlugResponse: {
            /** @description Успешно ли изменен slug */
            success: boolean;
            /**
             * @description Новый slug профиля
             * @example newusername
             */
            slug: string;
        };
        CheckSlugAvailabilityRequest: {
            /**
             * @description URL-слаг для проверки доступности
             * @example username
             */
            slug: string;
        };
        CheckSlugAvailabilityResponse: {
            /** @description Доступен ли slug для использования */
            available: boolean;
            /**
             * @description Сообщение о причине недоступности (если available = false)
             * @example This username is already taken
             */
            message?: string | null;
        };
        PublicProfile: {
            /** @description Уникальный идентификатор профиля */
            id: string;
            /** @description Имя профиля */
            name: string;
            /** @description URL-слаг профиля */
            slug: string;
            /**
             * Format: uri
             * @description URL аватара профиля
             */
            avatar_url: string | null;
            /** @description Краткое описание профиля */
            short_description: string;
            /** @description Полное описание профиля в формате TipTap JSON. Может быть null или JSONContent. */
            description: components["schemas"]["JSONContent"] | null;
            theme: components["schemas"]["ProfileTheme"];
            /**
             * @description Массив социальных сетей. Максимум 20 элементов.
             *     Порядок (order) должен быть уникальным для каждого элемента.
             */
            social_media: components["schemas"]["SocialMediaItem"][];
            /**
             * @description Массив блоков Bento. Максимум 50 элементов.
             *     ID и порядок (order) должны быть уникальными для каждого блока.
             */
            bento: components["schemas"]["BentoBlock"][];
        };
        GetProfileBySlugRequest: {
            /**
             * @description URL-слаг профиля для получения публичных данных
             * @example username
             */
            slug: string;
        };
        GetProfileBySlugResponse: components["schemas"]["PublicProfile"];
        /**
         * @description Refresh token должен быть передан в HTTP-only cookie с именем `refresh_token`.
         *     Тело запроса может быть пустым, так как токен читается из cookie.
         */
        RefreshTokenRequest: Record<string, never>;
        /**
         * @description Новый refresh token устанавливается в HTTP-only cookie с именем `refresh_token`.
         *     Cookie имеет флаги HttpOnly, Secure и SameSite=Strict для безопасности.
         */
        RefreshTokenResponse: {
            /** @description Новый JWT токен доступа */
            access_token: string;
        };
        /**
         * @description Refresh token для инвалидации читается из HTTP-only cookie с именем `refresh_token`.
         *     Тело запроса может быть пустым, так как токен читается из cookie.
         *     Сервер инвалидирует refresh token из cookie и все связанные токены пользователя.
         */
        LogoutRequest: Record<string, never>;
        LogoutResponse: {
            /** @description Успешно ли выполнен выход из системы */
            success: boolean;
            /**
             * @description Сообщение о результате операции
             * @example Successfully logged out
             */
            message?: string | null;
        };
        ErrorResponse: {
            /**
             * @description Код ошибки
             * @example VALIDATION_ERROR
             */
            error: string;
            /**
             * @description Сообщение об ошибке
             * @example Invalid email address
             */
            message: string;
            /** @description Дополнительные детали ошибки */
            details?: {
                [key: string]: unknown;
            };
        };
    };
    responses: {
        /** @description Ошибка валидации */
        ValidationError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Неверный формат email */
        InvalidEmail: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "VALIDATION_ERROR",
                 *       "message": "Invalid email format"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Неверный формат OTP */
        InvalidOtpFormat: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "VALIDATION_ERROR",
                 *       "message": "OTP must be 6 digits"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Неверный или истекший OTP код */
        InvalidOtp: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Неверный формат slug */
        InvalidSlugFormat: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Неверный формат пароля */
        InvalidPasswordFormat: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "VALIDATION_ERROR",
                 *       "message": "Password must be at least 8 characters with uppercase, lowercase and number"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Не авторизован */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "UNAUTHORIZED",
                 *       "message": "Authentication required"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Пользователь не найден */
        UserNotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "USER_NOT_FOUND",
                 *       "message": "User with this email does not exist"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Email уже занят */
        EmailAlreadyExists: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "EMAIL_ALREADY_EXISTS",
                 *       "message": "User with this email already exists"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Slug уже занят */
        SlugAlreadyTaken: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "SLUG_ALREADY_TAKEN",
                 *       "message": "This username is already taken"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Слишком много запросов */
        RateLimitExceeded: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "RATE_LIMIT_EXCEEDED",
                 *       "message": "Too many requests. Please try again later."
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Внутренняя ошибка сервера */
        InternalServerError: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Неверный пароль */
        WrongPassword: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "WRONG_PASSWORD",
                 *       "message": "Current password is incorrect"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Новый пароль совпадает со старым */
        SamePassword: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "SAME_PASSWORD",
                 *       "message": "New password must be different from old password"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Пароли не совпадают */
        PasswordsDoNotMatch: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "VALIDATION_ERROR",
                 *       "message": "New password and confirmation do not match"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Пароль уже установлен */
        PasswordAlreadyExists: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "PASSWORD_ALREADY_EXISTS",
                 *       "message": "Account already has a password"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Новый email совпадает со старым */
        SameEmail: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "SAME_EMAIL",
                 *       "message": "New email must be different from current email"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Новый slug совпадает со старым */
        SameSlug: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "SAME_SLUG",
                 *       "message": "New slug must be different from current slug"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Превышен лимит смены slug */
        SlugChangeLimitExceeded: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "SLUG_CHANGE_LIMIT_EXCEEDED",
                 *       "message": "Slug can be changed only once per 7 days"
                 *     }
                 */
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Неверный или истекший refresh token */
        InvalidRefreshToken: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
