/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Profile: {
      /** @description Уникальный идентификатор профиля */
      id: string;
      /** @description Имя профиля */
      name: string;
      /** @description URL-слаг профиля */
      slug: string;
      /**
       * Format: email
       * @description Email пользователя
       */
      email: string;
      /**
       * Format: date-time
       * @description Дата создания профиля
       */
      created_at: string;
      /**
       * Format: uri
       * @description URL аватара профиля
       */
      avatar_url?: string | null;
      /** @description Защищен ли профиль паролем */
      protected_by_password: boolean;
      /** @description Краткое описание профиля */
      short_description: string;
      /** @description Полное описание профиля в формате TipTap JSON */
      description?: components["schemas"]["JSONContent"];
      theme: components["schemas"]["ProfileTheme"];
      /** @description Список социальных сетей */
      social_media: components["schemas"]["SocialMediaItem"][];
      /** @description Список блоков Bento */
      bento: components["schemas"]["BentoBlock"][];
    };
    ProfileMainEditableFields: {
      name: string;
      slug: string;
      /** Format: email */
      email: string;
      /** Format: date-time */
      created_at: string;
      /** Format: uri */
      avatar_url?: string | null;
      protected_by_password: boolean;
      short_description: string;
      description?: components["schemas"]["JSONContent"];
      theme: components["schemas"]["ProfileTheme"];
      social_media: components["schemas"]["SocialMediaItem"][];
      bento: components["schemas"]["BentoBlock"][];
    };
    ProfileTheme: {
      font: components["schemas"]["Font"];
      theme: components["schemas"]["Theme"];
      /** @description Показывать ли размытие аватара */
      show_avatar_blur: boolean;
      /** @description Радиус скругления границ */
      border_radius: number;
      /** @description Ширина границы */
      border_width: number;
    };
    /**
     * @description Доступные шрифты
     * @enum {string}
     */
    Font:
      | "open-runde"
      | "inter"
      | "gilroy"
      | "vollkorn"
      | "jetbrains-mono"
      | "montserrat"
      | "oswald"
      | "caveat";
    /**
     * @description Доступные темы оформления
     * @enum {string}
     */
    Theme:
      | "light"
      | "dark"
      | "green"
      | "pink"
      | "blue"
      | "purple"
      | "golden"
      | "dark-blue"
      | "dark-slate"
      | "dark-forest"
      | "dark-plum"
      | "dark-amber"
      | "dark-ink"
      | "dark-copper"
      | "dark-olive"
      | "dark-indigo"
      | "teal"
      | "coral"
      | "lavender"
      | "sand"
      | "mint"
      | "sky"
      | "ice"
      | "peach";
    SocialMediaItem: {
      platform: components["schemas"]["SocialMediaPlatform"];
      /** @description Идентификатор пользователя на платформе */
      slug: string;
      /** @description Порядок отображения */
      order: number;
    };
    /**
     * @description Доступные платформы социальных сетей
     * @enum {string}
     */
    SocialMediaPlatform:
      | "instagram"
      | "telegram"
      | "x"
      | "bluesky"
      | "discord"
      | "dribbble"
      | "facebook"
      | "github"
      | "linkedin"
      | "tiktok"
      | "threads"
      | "pinterest"
      | "medium"
      | "youtube"
      | "messenger"
      | "reddit"
      | "snapchat"
      | "spotify"
      | "tumblr"
      | "twitch"
      | "vk"
      | "whatsapp";
    BentoBlock:
      | components["schemas"]["BentoBlockGallery"]
      | components["schemas"]["BentoBlockLink"]
      | components["schemas"]["BentoBlockText"]
      | components["schemas"]["BentoBlockMap"];
    BentoBlockBase: {
      /** @description Уникальный идентификатор блока */
      id: string;
      size: components["schemas"]["BentoBlockSize"];
      /** @description Порядок отображения блока */
      order: number;
      style: components["schemas"]["BentoBlockStyle"];
      type: components["schemas"]["BentoBlockType"];
    };
    BentoBlockGallery: components["schemas"]["BentoBlockBase"] & {
      /** @enum {string} */
      type?: "gallery";
      properties?: components["schemas"]["BentoBlockPropertiesGallery"];
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "gallery";
    };
    BentoBlockLink: components["schemas"]["BentoBlockBase"] & {
      /** @enum {string} */
      type?: "link";
      properties?: components["schemas"]["BentoBlockPropertiesLink"];
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "link";
    };
    BentoBlockText: components["schemas"]["BentoBlockBase"] & {
      /** @enum {string} */
      type?: "text";
      properties?: components["schemas"]["BentoBlockPropertiesText"];
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "text";
    };
    BentoBlockMap: components["schemas"]["BentoBlockBase"] & {
      /** @enum {string} */
      type?: "map";
      properties?: components["schemas"]["BentoBlockPropertiesMap"];
    } & {
      /**
       * @description discriminator enum property added by openapi-typescript
       * @enum {string}
       */
      type: "map";
    };
    /**
     * @description Размер блока Bento
     * @enum {string}
     */
    BentoBlockSize: "2x2" | "4x1" | "2x4" | "4x2" | "4x4" | "dynamic";
    /**
     * @description Стиль блока Bento
     * @enum {string}
     */
    BentoBlockStyle: "plain" | "shadow" | "outline" | "transparent";
    /**
     * @description Тип блока Bento
     * @enum {string}
     */
    BentoBlockType: "gallery" | "link" | "text" | "map";
    BentoBlockPropertiesGallery: {
      /** @description Массив URL изображений для галереи */
      media: string[];
    };
    BentoBlockPropertiesLink: {
      /**
       * Format: uri
       * @description URL ссылки
       */
      url: string;
      /** @description Заголовок ссылки */
      title: string;
      /** @description Валидна ли ссылка */
      url_valid: boolean;
    };
    BentoBlockPropertiesText: {
      /** @description Содержимое текстового блока в формате TipTap JSON */
      content: components["schemas"]["JSONContent"];
    };
    BentoBlockPropertiesMap: {
      theme: components["schemas"]["BentoBlockMapThemesOptions"];
      /** @description Показывать ли подписи на карте */
      labels: boolean;
      /** @description Разрешены ли взаимодействия с картой */
      interactions: boolean;
      /** @description Уровень масштабирования карты */
      zoom: number;
      /** @description Заголовок карты */
      title: string;
      titleAlign: components["schemas"]["BentoBlockMapTitleAlign"];
      /**
       * Format: float
       * @description Широта центра карты
       */
      latitude: number;
      /**
       * Format: float
       * @description Долгота центра карты
       */
      longitude: number;
    };
    /**
     * @description Тема карты (auto означает автоматический выбор на основе темы профиля)
     * @enum {string}
     */
    BentoBlockMapThemesOptions: "auto" | "light" | "dark" | "positron";
    /**
     * @description Выравнивание заголовка карты
     * @enum {string}
     */
    BentoBlockMapTitleAlign:
      | "bottom-left"
      | "bottom-center"
      | "bottom-right"
      | "top-left"
      | "top-center"
      | "top-right";
    /** @description Структурированный JSON контент из TipTap редактора */
    JSONContent: {
      /** @description Тип узла (doc, paragraph, heading, text и т.д.) */
      type?: string;
      /** @description Атрибуты узла */
      attrs?: {
        [key: string]: unknown;
      };
      /** @description Вложенное содержимое узла */
      content?: components["schemas"]["JSONContent"][];
      /** @description Текстовое содержимое для текстовых узлов */
      text?: string;
      /** @description Маркировки текста (жирный, курсив и т.д.) */
      marks?: Record<string, never>[];
    } & {
      [key: string]: unknown;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
